package org.example.sysdesign.api.util;

import org.example.sysdesign.model.Staffmember;
import java.util.Date;
import java.util.ArrayList;


/**
 * When creating a new Staffmember, or updating a Staffmember, some attributes are system generated.
 *
 * This utility class represents the input for Staffmember write operations and facilitates creating
 * or setting derived Staffmember instances.
    @param name - name of the staffmember
    @param accepted - date of acceptance
    @param type - type of staffmember: guard, guide or cleaning staff
    @param planned - day of planned shift

 */
public record StaffmemberInput(String name, Date accepted, String type, Date planned) {

    /**
     * Create a new Stafmember instance or update an existing one, based on the content of this StaffInput.
        @param id - Id for the staffmember (should be generated by the storage driver).
        @param name - name of the staffmember
        @param accepted - date of acceptance
        @param type - type of staffmember: guard, guide or cleaning staff
        @return a new Staffmember instance or an updated one
     */


    public Staffmember createNewStaffmember() {
        return new Staffmember(null, this.name, this.accepted, this.type, this.planned);
    }

    public Staffmember updateStaffmember(Staffmember existingStaffMember) {
        return new Staffmember(existingStaffMember.id, 
                                    this.name,
                                    this.accepted,
                                    this.type,
                                    this.planned);
    }

    public Date  getPlanned() {
        return this.planned;
    }
}
